# Generated by Django 5.2.16 on 2026-07-24 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_enhance_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='address',
        ),
    ]
